# Generated by Django 3.1.3 on 2020-11-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
    ]
