# Generated by Django 3.1.3 on 2020-11-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_remove_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
