# Generated by Django 3.1.3 on 2020-11-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0003_team_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='data',
        ),
    ]
