# Generated by Django 3.1.3 on 2020-11-04 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20201105_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.card'),
        ),
    ]
