# Generated by Django 3.1.3 on 2020-11-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_auto_20201105_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='working',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
