# Generated by Django 3.1.3 on 2020-11-05 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0005_auto_20201105_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Card title'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Item title'),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='working',
            field=models.BooleanField(default=True, verbose_name='Currently working'),
        ),
        migrations.AlterField(
            model_name='carditemcomment',
            name='body',
            field=models.TextField(verbose_name='Comment text'),
        ),
        migrations.AlterField(
            model_name='carditemcomment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='working',
            field=models.BooleanField(default=True, verbose_name='Currently working'),
        ),
    ]
