# Generated by Django 3.1.3 on 2020-11-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20201105_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('default', 'Default'), ('black', 'Black'), ('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue'), ('violet', 'Violet'), ('red', 'Red'), ('yellow', 'Yellow')], default='default', max_length=15),
        ),
    ]
