# Generated by Django 3.1.3 on 2020-11-05 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0007_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auth.user', verbose_name='Main Creator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('default', 'Default'), ('black', 'Black'), ('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue'), ('violet', 'Violet'), ('red', 'Red'), ('yellow', 'Yellow')], default='default', max_length=15, verbose_name='Project UI color'),
        ),
    ]
