# Generated by Django 3.1.3 on 2020-11-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_auto_20201105_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
